http://localhost:3003/recipes

###

http://localhost:3003/recipes?title=a&sort=title&orde=DESC

###

http://localhost:3003/recipes?title=a&sort=title&orde=desc&page=1

###

http://localhost:3003/user?name=amandi

###

http://localhost:3003/user/dasdas@dasda.com

###

http://localhost:3003/user/orde?sort=name&orde=DESC

###

http://localhost:3003/user/pag?page=3

###

http://localhost:3003/user/allEndPoint?name=a&sort=id&orde=ASC
